### ISSUE TITLE
Extending muscle-BIDS: a BIDS-derived standard and conversion tool specific for quantitative muscle MRI

### ISSUE THREAD

**Issue by fsantini** [mrathon/idea-pitches#10]
> Please fill in the below table to submit your project proposal!

| Field                | Value            |
|:--------------|:-------------|
| Project Name |   *muscle-BIDS*    |
| Description    |   *Muscle-BIDS is both a standard and a set of python tools for the establishment of a standardized, multivendor format for the processing of quantitative muscle MRI data. It is a project of the [ORMIR](https://ormircommunity.github.io/) (Open and Reproducible MSK Imaging Research) community* |
| URL(s)            |   *https://muscle-bids.github.io/* |
| GitHub handles   |    *muscle-bids* |
| Twitter handles   |    *@mrifranz @ORMIR_Community* |
| Image            |    ![muscle-bids icon](https://avatars.githubusercontent.com/u/107402526?s=400&u=e60391c7ba71c47896ac7780a6d62f16411ba3a9&v=4) |

**Comment by agahkarakuzu** [comment]
Thank you so much for the submission @fsantini ! The logo looks great, so happy to see there's an effort in this direction.
