### ISSUE TITLE
Virtual Scanner

### ISSUE THREAD

**Issue by tonggehua** [mrathon/idea-pitches#11]
> Please fill in the below table to submit your project proposal!

| Field                | Value            |
|:--------------|:-------------|
| Project Name |   Virtual Scanner Research Mode   |
| Description    |   Virtual Scanner research mode aims to provide a web GUI for its Bloch simulation pipeline that enables setting of sequence (in Pulseq format), phantoms, and hardware map, with additional Pulseq sequence viewing/editing capabilities. We also plan to enable a console option that connects to MaRCoS to operate a tabletop system so that simulated and acquired data can be compared line by line.  |
| URL(s)            |   www.github.com/imr-framework/virtual-scanner, www.github.com/imr-framework/vs-tabletop |
| GitHub handles   |   @tonggehua |
| Twitter handles   |   @GehuaT |
| Image            |   ![virtual_scanner_logo_v1](https://user-images.githubusercontent.com/31249056/221929418-41451b84-2200-46a3-9131-c9782160ca4e.png) |

**Comment by agahkarakuzu** [comment]
Thank you @tonggehua! We will start updating the website soon to include new project submissions.
