### ISSUE TITLE
MRI QA tools written in PulSeq for reproducible MRI scanner testing across vendors and sites

### ISSUE THREAD

**Issue by jaystock** [mrathon/idea-pitches#12]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   *MRI QA tools written in PulSeq for reproducible MRI scanner testing across vendors and sites*    |
| Description    |   * Often we try to reproduce a measurement on a different scanner platform using just a few parameters reported in a paper.  This poses a barrier to reproducible research and apples-to-apples scanner performance comparisons.  We need standardized Quality Assurance and calibration pulse sequences and post-processing pipelines that can be easily run on any MRI scanner at any site.  Such tools are needed for measuring B0 maps; B1 maps; T1, T2, and T2*; ADC maps; gradient linearity; magnet homogeneity; RF receive SNR; eddy currents; and other important system properties.  PulSeq provides a convenient format for standardizing these measurements across different consoles.  Ideally, the PulSeq QA tools would be paired with open-source recipes for standard phantoms that could be used at different sites to run the QA protocols.  Finally, the image data would be stored in ISMRMRD format so that a standardized set of image processing tools could be run on the data to provide each parameter map of interest. * |
| URL(s)            |   *Your relevant URL(s) here* |
| GitHub handles   |    *jaystock* |
| Twitter handles   |    *Your relevant Twitter handles here* |
| Image            |    *Your project pitch icon here* |

**Comment by agahkarakuzu** [comment]
Thank you so much @jaystock! 

I will go through these issues to update the website soon.
