### ISSUE TITLE
Gadgetron Starter Project

### ISSUE THREAD

**Issue by rajramasawmy** [mrathon/idea-pitches#13]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   **Gadgetron Starter Project**   |
| Description    |   The gadgetron starter project provides a guide for new developers to work with the gadgetron framework. The starter project aims to provide examples and guidance for non-c++ experts in how to use the gadgetron toolbox, and how to make research tools without having to re-invent MRI reconstruction. The aims for this project in the mrathon 2023: 1) Completion of starter project documentation, 2) Addition of research examples, 3) Install how-to guides |
| URL(s)            |   https://github.com/gadgetron/gadgetron-starter |
| GitHub handles   |    @Andrew-Dupuis, @rajramasawmy , @valeryozenne, @ahsanjav |
| Twitter handles   |   |
| Image            |  [icon](https://avatars.githubusercontent.com/u/9702817?s=200&v=4)  |

**Comment by agahkarakuzu** [comment]
Thank you @rajramasawmy ! I will update the website to include this soon.
