### ISSUE TITLE
PyPulseq

### ISSUE THREAD

**Issue by sravan953** [mrathon/idea-pitches#14]
> Please fill in the below table to submit your project proposal!

| Field                | Value            |
|:--------------|:-------------|
| Project Name |  PyPulseq  |
| Description    |   Pulse sequence design is a significant component of MRI research. However, multi-vendor studies require researchers to be acquainted with each hardware platform's programming environment. PyPulseq enables vendor-neutral pulse sequence design in Python. The pulse sequences can be exported as a `.seq` file to be run on Siemens/GE/Bruker hardware by leveraging their respective Pulseq interpreters. This tool is targeted at MRI pulse sequence designers, researchers, students, and other interested users. |
| URL(s)            |  https://github.com/imr-framework/pypulseq |
| GitHub handles   |   @sravan953 |
| Twitter handles   |   [@sravan953](https://twitter.com/sravan953) |
| Image            |  ![PyPulseq logo](https://raw.githubusercontent.com/imr-framework/pypulseq/dev/logo_transparent.png)  |

**Comment by agahkarakuzu** [comment]
Dear @sravan953 thank you for this amazing project pitch! 

We are finalizing some details regarding the schedule of talks and events, then I'll make a major update to the website including this project. 

See you in Toronto!
