### ISSUE TITLE
OpenSourceImaging Wiki

### ISSUE THREAD

**Issue by opensourceimaging** [mrathon/idea-pitches#3]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   Open Source Imaging Wiki    |
| Description    |   Our brand new OpenSourceImaging Wiki is installed and ready to grow. Let's make of it an open source knowledge base around MR research and development. It will be open and free to all, now and forever, linking open source tools and educational content. We want it to be a practical space. Share your hands-on tips from engineering to coding; Discuss scientific reproducbility issues and solutions. Brainstorm a roadmap towards open source medical devices and everything else that your open source heart desires. Now we need you to start filling this beauty. Help us with the structure, template, design etc. Start filling in content based on your expertise and link it to the open source tools that you like, if its image reconstruction, hardware development, MR basics, coding basics, doesn't matter, whatever information you believe others might benefit from. Be creative, maybe you want to hide some funny easter eggs on the wiki? You decide the content and determine the direction of the first steps of our new baby. Should be easy and should be fun. Our moto: From the community for the community |
| URL(s)            |   https://www.opensourceimaging.org/ https://wiki.opensourceimaging.org/HomePage  |
| GitHub handles   |    @opensourceimaging  |
| Twitter handles   |    *Your relevant Twitter handles here* |
| Image            |  ![OSI-community-circle](https://user-images.githubusercontent.com/20105914/54762645-c58d8380-4bf4-11e9-8415-dc6a0c69d23a.jpg)
  |

**Comment by RPellicer** [comment]
I like it! Thanks Lukas! It is cheerful and inviting.
Could I propose a couple of changes? Mostly shortening the sentences and making paragraphs for readability. Something like:

> Our brand new OpenSourceImaging Wiki is ready to grow. Let’s make of it an open source knowledge base around MR research and development. It will be open and free to all, now and forever, linking open source tools and educational content. 

>We want it to be a practical space. Share your hands-on tips from engineering to coding; Discuss scientific reproducibility issues and solutions. Display your current open source hardware and software development projects; Brainstorm a road-map towards open source medical devices and everything else that your open source heart desires. 

>Now we need you to start filling this beauty. How could you help?

>- Create: Do you have or are you developing an MR related open source hardware and software development project? Bring it on! Start filling in content based on your expertise and link it to the open source tools that you like, Whether it is image reconstruction, hardware development, MR basics, coding basics, doesn't matter, be creative. Maybe you want to hide some funny Easter eggs on the wiki?

>- Decide: Help us with the structure, template, design etc. You decide the content and determine the direction of the first steps of our new baby. Should be easy and should be fun. Our motto: From the community to the community.>
