### ISSUE TITLE
DWI visualization

### ISSUE THREAD

**Issue by StongeEtienne** [mrathon/idea-pitches#7]
| Field                | Value            |
|:--------------|:-------------|
| Project Name |   DWI visualization   |
| Description    |   Diffusion MRI (dMRI) / Diffusion weighted image (DWI) visualization,  developing some functions for DWI, streamlines and surfaces rendering with VTK in python. See FURY and DIPY project. |
| URL(s)            |   http://fury.gl/  https://nipy.org/dipy/ |
| GitHub handles   |  https://github.com/StongeEtienne |
| Image            |  ![my8000_t_c80r1920_all](https://user-images.githubusercontent.com/5375393/56460294-93e01780-636e-11e9-9e0d-646126645286.jpg) |

**Comment by StongeEtienne** [comment]
https://docs.google.com/presentation/d/1z2gxr6tmap3ImwwcaFEyCQQo3Y480t-T4eCbEa4LoBI/edit?usp=sharing

https://drive.google.com/open?id=1HJhJA-GxEQ3HNsL7VWIjvY7TL-766JmF

**Comment by StongeEtienne** [comment]
![fodf_d4](https://user-images.githubusercontent.com/5375393/57556997-89e67e80-7346-11e9-94ee-af345e14219b.gif)

**Comment by djoerch** [comment]
![sl_video3](https://user-images.githubusercontent.com/3168589/57557249-62dc7c80-7347-11e9-8221-694fa5af780e.gif)
